---
- name: Day 4 Challenge
  hosts: planetexpress
  gather_facts: yes

  tasks:
  - name: Set authorized key taken from file
    become: yes
    ansible.posix.authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    register: student_key
    notify: oopsies handler
    when: ansible_distribution == "Ubuntu"

  - name: create astronomy directory
    file:
      path: "/home/{{ ansible_user }}/astronomy/"
      state: directory

  - name: get APOD
    get_url:
      url: https://www.nasa.gov/sites/default/files/thumbnails/image/apod.jpg
      dest: "/home/{{ ansible_user }}/astronomy/"

  handlers:
  - name: oopsies handler
    debug:
        var: student_key
        
