---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts

  tasks:
    - name: Configure mission orders
      template:
        src: templates/mission-orders.txt.j2
        dest: ~/{{ item.mission }}-mission-orders.txt
      loop: 
        - mission: primary
          planet: luna park
        - mission: secondary
          planet: cineplex 14

